name: Restore Repository
permissions: write-all

on:
  workflow_dispatch:
    inputs:
      otp_code:
        description: 'OTP CODE - Use it as blank for first run. Get OTP code via email and run again with OTP code. OTP code expires after 90 seconds'
        required: false

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Repository
        uses: berkayy-atas/marketplace-test-workflow-restore@latest
        with:
          activation_code: ${{ secrets.ACTIVATION_CODE }}
          encryption_key: ${{ secrets.ENCRYPTION_KEY }}
          otp_code: ${{ github.event.inputs.OTP_CODE }}
          record_id: 'string'
